const STATUS_CREATED = 201;

const ERROR_BAD_REQUEST = 400;

const ERROR_NOT_FOUND = 404;

const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  STATUS_CREATED,
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
};
